# Generated by Django 2.1.5 on 2019-03-01 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(default='', max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('platinum_seats', models.IntegerField(default=0)),
                ('gold_seats', models.IntegerField(default=0)),
                ('silver_seats', models.IntegerField(default=0)),
                ('time_prefrence', models.CharField(choices=[('9-12', '9-12'), ('12-3', '12-3'), ('3-6', '6-9'), ('6-12', '6-12')], default=0, max_length=10)),
                ('booking_date', models.DateField(null=True)),
                ('each_entry_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=200)),
                ('venuname', models.CharField(default='', help_text='add venue name', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('discription', models.TextField(default='')),
                ('slug', models.SlugField(unique=True)),
                ('platinum_seats', models.IntegerField(default=0)),
                ('gold_seats', models.IntegerField(default=0)),
                ('silver_seats', models.IntegerField(default=0)),
                ('platinum_price', models.IntegerField(default=0)),
                ('gold_price', models.IntegerField(default=0)),
                ('silver_price', models.IntegerField(default=0)),
                ('last_date', models.DateField(default=datetime.datetime(2019, 3, 1, 16, 55, 11, 457282, tzinfo=utc))),
                ('image', models.FileField(upload_to='home/movies/')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('slug', 'name')},
        ),
    ]
