# Generated by Django 2.1.5 on 2019-03-01 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190301_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 15, 0, 588258, tzinfo=utc)),
        ),
    ]
