# Generated by Django 2.1.5 on 2019-03-01 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_event_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 19, 18, 6, 618130, tzinfo=utc)),
        ),
    ]
