# Generated by Django 2.1.5 on 2019-03-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190302_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time_prefrence',
            new_name='time_preference',
        ),
    ]
