# Generated by Django 2.1.5 on 2019-03-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190302_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='each_entry_date',
        ),
    ]
