# Generated by Django 2.1.5 on 2019-03-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190308_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Circus'},
        ),
    ]
