# Generated by Django 2.1.5 on 2019-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190309_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'parking'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_preference',
            field=models.CharField(choices=[('Moring 10-12', 'Moring 10-12'), ('12-2 ', '12-2'), ('2-4', '2-4'), ('4-6', '4-6'), ('6-8', '6-8'), ('night 8-10', 'night 8-10')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='parking place'),
        ),
    ]
